meta_product_name: "Howinanny"
meta_title: "Howinanny - Créateur de vacances de rêves"
meta_description: "Howinanny vous propose de trouver la meilleure nounou qui vous accompagnera pendant vos vacances"
meta_image: "home-howinanny.png" # should exist in `app/assets/images/`
